services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_todo
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Testing@123"
      ACCEPT_EULA: "Y"
