# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 765)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"background-image: url(:/icon/img/login-background-3.jpg);\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"background-size: cover; /* Stretches image to match window size */ ;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setStyleSheet("#page {\n"
"background-image: url(:/icon/img/login-background-3.jpg);\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"background-size: cover; /* Stretches image to match window size */ ;\n"
"}")
        self.login_page.setObjectName("login_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.login_page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.login_main_frame = QtWidgets.QFrame(self.login_page)
        self.login_main_frame.setStyleSheet("QFrame {border: none}\n"
"")
        self.login_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_main_frame.setObjectName("login_main_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.login_main_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.support_frame = QtWidgets.QFrame(self.login_main_frame)
        self.support_frame.setStyleSheet("")
        self.support_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.support_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.support_frame.setObjectName("support_frame")
        self.horizontalLayout.addWidget(self.support_frame)
        self.login_frame = QtWidgets.QFrame(self.login_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_frame.sizePolicy().hasHeightForWidth())
        self.login_frame.setSizePolicy(sizePolicy)
        self.login_frame.setMinimumSize(QtCore.QSize(350, 0))
        self.login_frame.setMaximumSize(QtCore.QSize(16777215, 500))
        self.login_frame.setStyleSheet("#login_frame{\n"
"background-color: rgba(255, 255, 255, 0.2);\n"
"border-radius: 20px}")
        self.login_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_frame.setObjectName("login_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.login_frame)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.login_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_2 = QtWidgets.QFrame(self.login_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setSpacing(30)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setTabletTracking(True)
        self.lineEdit.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 1px solid #33fcff;\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 7px\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setTabletTracking(True)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_2.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 1px solid #33fcff;\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 7px\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_4.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.frame_5 = QtWidgets.QFrame(self.login_frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.login_button = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_button.sizePolicy().hasHeightForWidth())
        self.login_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("#login_button {\n"
"    background-color: #335eff;       /* Blue background */\n"
"    color: white;                   /* White text */\n"
"    font-size: 16px;                /* Text size */\n"
"    font-weight: bold;              /* Bold text */\n"
"    border:none;      /* Border with a darker blue */\n"
"    border-radius: 5px;            /* Rounded corners */\n"
"    padding: 10px 20px;             /* Internal padding */\n"
"}\n"
"\n"
"#login_button:hover {\n"
"    background-color: #5e33ff;      /* Darker blue on hover */\n"
"}\n"
"\n"
"#login_button:pressed {\n"
"    background-color: #350e95;      /* Dark blue when pressed */\n"
"    color: #e6e6e6;                 /* Slightly lighter text */\n"
"}\n"
"")
        self.login_button.setObjectName("login_button")
        self.verticalLayout_5.addWidget(self.login_button)
        self.verticalLayout_2.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.login_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.notify_message_3 = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notify_message_3.sizePolicy().hasHeightForWidth())
        self.notify_message_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setBold(True)
        font.setWeight(75)
        self.notify_message_3.setFont(font)
        self.notify_message_3.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border: none;\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 7px\n"
"")
        self.notify_message_3.setText("")
        self.notify_message_3.setAlignment(QtCore.Qt.AlignCenter)
        self.notify_message_3.setObjectName("notify_message_3")
        self.verticalLayout_19.addWidget(self.notify_message_3)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)
        self.frame_6 = QtWidgets.QFrame(self.login_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        font.setUnderline(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border: none;\n"
"color: white")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        font.setUnderline(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border: none;\n"
"color: white")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.login_frame)
        self.support_frame_2 = QtWidgets.QFrame(self.login_main_frame)
        self.support_frame_2.setStyleSheet("")
        self.support_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.support_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.support_frame_2.setObjectName("support_frame_2")
        self.horizontalLayout.addWidget(self.support_frame_2)
        self.verticalLayout_6.addWidget(self.login_main_frame)
        self.stackedWidget.addWidget(self.login_page)
        self.Signup_frame = QtWidgets.QWidget()
        self.Signup_frame.setStyleSheet("#page_2 {\n"
"background-image: url(:/icon/img/login-background-3.jpg);\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"background-size: cover; /* Stretches image to match window size */ ;\n"
"}")
        self.Signup_frame.setObjectName("Signup_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Signup_frame)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.signup_main_frame = QtWidgets.QFrame(self.Signup_frame)
        self.signup_main_frame.setStyleSheet("QFrame {border: none}\n"
"")
        self.signup_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signup_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signup_main_frame.setObjectName("signup_main_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.signup_main_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.support_frame_4 = QtWidgets.QFrame(self.signup_main_frame)
        self.support_frame_4.setStyleSheet("")
        self.support_frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.support_frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.support_frame_4.setObjectName("support_frame_4")
        self.horizontalLayout_3.addWidget(self.support_frame_4)
        self.signup_frame = QtWidgets.QFrame(self.signup_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signup_frame.sizePolicy().hasHeightForWidth())
        self.signup_frame.setSizePolicy(sizePolicy)
        self.signup_frame.setMinimumSize(QtCore.QSize(350, 0))
        self.signup_frame.setMaximumSize(QtCore.QSize(16777215, 500))
        self.signup_frame.setStyleSheet("#signup_frame{\n"
"background-color: rgba(255, 255, 255, 0.2);\n"
"border-radius: 20px}")
        self.signup_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signup_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signup_frame.setObjectName("signup_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.signup_frame)
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.signup_title_frame = QtWidgets.QFrame(self.signup_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signup_title_frame.sizePolicy().hasHeightForWidth())
        self.signup_title_frame.setSizePolicy(sizePolicy)
        self.signup_title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signup_title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signup_title_frame.setObjectName("signup_title_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.signup_title_frame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.signup_title = QtWidgets.QLabel(self.signup_title_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signup_title.sizePolicy().hasHeightForWidth())
        self.signup_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.signup_title.setFont(font)
        self.signup_title.setStyleSheet("color: white")
        self.signup_title.setObjectName("signup_title")
        self.verticalLayout_8.addWidget(self.signup_title)
        self.verticalLayout_7.addWidget(self.signup_title_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_9 = QtWidgets.QFrame(self.signup_frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setSpacing(30)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.username_input = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_input.sizePolicy().hasHeightForWidth())
        self.username_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.username_input.setFont(font)
        self.username_input.setTabletTracking(True)
        self.username_input.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.username_input.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 1px solid #33fcff;\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 7px\n"
"")
        self.username_input.setText("")
        self.username_input.setObjectName("username_input")
        self.verticalLayout_9.addWidget(self.username_input)
        self.pass_input = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pass_input.sizePolicy().hasHeightForWidth())
        self.pass_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.pass_input.setFont(font)
        self.pass_input.setTabletTracking(True)
        self.pass_input.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.pass_input.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 1px solid #33fcff;\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 7px\n"
"")
        self.pass_input.setText("")
        self.pass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_input.setObjectName("pass_input")
        self.verticalLayout_9.addWidget(self.pass_input)
        self.confirm_pass_input = QtWidgets.QLineEdit(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setBold(True)
        font.setWeight(75)
        self.confirm_pass_input.setFont(font)
        self.confirm_pass_input.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 1px solid #33fcff;\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 7px\n"
"")
        self.confirm_pass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_pass_input.setObjectName("confirm_pass_input")
        self.verticalLayout_9.addWidget(self.confirm_pass_input)
        self.verticalLayout_7.addWidget(self.frame_9, 0, QtCore.Qt.AlignTop)
        self.signup_button_frame = QtWidgets.QFrame(self.signup_frame)
        self.signup_button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signup_button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signup_button_frame.setObjectName("signup_button_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.signup_button_frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.signup_button = QtWidgets.QPushButton(self.signup_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signup_button.sizePolicy().hasHeightForWidth())
        self.signup_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.signup_button.setFont(font)
        self.signup_button.setStyleSheet("#signup_button {\n"
"    background-color: #335eff;       /* Blue background */\n"
"    color: white;                   /* White text */\n"
"    font-size: 16px;                /* Text size */\n"
"    font-weight: bold;              /* Bold text */\n"
"    border:none;      /* Border with a darker blue */\n"
"    border-radius: 5px;            /* Rounded corners */\n"
"    padding: 10px 20px;             /* Internal padding */\n"
"}\n"
"\n"
"#signup_button:hover {\n"
"    background-color: #5e33ff;      /* Darker blue on hover */\n"
"}\n"
"\n"
"#signup_button:pressed {\n"
"    background-color: #350e95;      /* Dark blue when pressed */\n"
"    color: #e6e6e6;                 /* Slightly lighter text */\n"
"}\n"
"")
        self.signup_button.setObjectName("signup_button")
        self.verticalLayout_10.addWidget(self.signup_button)
        self.verticalLayout_7.addWidget(self.signup_button_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.notify_frame = QtWidgets.QFrame(self.signup_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notify_frame.sizePolicy().hasHeightForWidth())
        self.notify_frame.setSizePolicy(sizePolicy)
        self.notify_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.notify_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.notify_frame.setObjectName("notify_frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.notify_frame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.notify_message = QtWidgets.QLineEdit(self.notify_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notify_message.sizePolicy().hasHeightForWidth())
        self.notify_message.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setBold(True)
        font.setWeight(75)
        self.notify_message.setFont(font)
        self.notify_message.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border: none;\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 7px\n"
"")
        self.notify_message.setText("")
        self.notify_message.setAlignment(QtCore.Qt.AlignCenter)
        self.notify_message.setObjectName("notify_message")
        self.verticalLayout_12.addWidget(self.notify_message, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_7.addWidget(self.notify_frame, 0, QtCore.Qt.AlignHCenter)
        self.frame_11 = QtWidgets.QFrame(self.signup_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.back_to_login = QtWidgets.QPushButton(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        font.setUnderline(True)
        self.back_to_login.setFont(font)
        self.back_to_login.setStyleSheet("border: none;\n"
"color: white")
        self.back_to_login.setObjectName("back_to_login")
        self.horizontalLayout_4.addWidget(self.back_to_login, 0, QtCore.Qt.AlignLeft)
        self.change_pass_button = QtWidgets.QPushButton(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        font.setUnderline(True)
        self.change_pass_button.setFont(font)
        self.change_pass_button.setStyleSheet("border: none;\n"
"color: white")
        self.change_pass_button.setObjectName("change_pass_button")
        self.horizontalLayout_4.addWidget(self.change_pass_button, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_7.addWidget(self.frame_11)
        self.horizontalLayout_3.addWidget(self.signup_frame)
        self.support_frame_3 = QtWidgets.QFrame(self.signup_main_frame)
        self.support_frame_3.setStyleSheet("")
        self.support_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.support_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.support_frame_3.setObjectName("support_frame_3")
        self.horizontalLayout_3.addWidget(self.support_frame_3)
        self.verticalLayout_11.addWidget(self.signup_main_frame)
        self.stackedWidget.addWidget(self.Signup_frame)
        self.reset_pass_page = QtWidgets.QWidget()
        self.reset_pass_page.setStyleSheet("#reset_pass_page {\n"
"background-image: url(:/icon/img/login-background-3.jpg);\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"background-size: cover; /* Stretches image to match window size */ ;\n"
"}")
        self.reset_pass_page.setObjectName("reset_pass_page")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.reset_pass_page)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.reset_pass_main_frame = QtWidgets.QFrame(self.reset_pass_page)
        self.reset_pass_main_frame.setStyleSheet("QFrame {border: none}\n"
"")
        self.reset_pass_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.reset_pass_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.reset_pass_main_frame.setObjectName("reset_pass_main_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.reset_pass_main_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.support_frame_5 = QtWidgets.QFrame(self.reset_pass_main_frame)
        self.support_frame_5.setStyleSheet("")
        self.support_frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.support_frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.support_frame_5.setObjectName("support_frame_5")
        self.horizontalLayout_5.addWidget(self.support_frame_5)
        self.reset_pass_frame = QtWidgets.QFrame(self.reset_pass_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_pass_frame.sizePolicy().hasHeightForWidth())
        self.reset_pass_frame.setSizePolicy(sizePolicy)
        self.reset_pass_frame.setMinimumSize(QtCore.QSize(350, 0))
        self.reset_pass_frame.setMaximumSize(QtCore.QSize(16777215, 500))
        self.reset_pass_frame.setStyleSheet("#reset_pass_frame{\n"
"background-color: rgba(255, 255, 255, 0.2);\n"
"border-radius: 20px}")
        self.reset_pass_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.reset_pass_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.reset_pass_frame.setObjectName("reset_pass_frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.reset_pass_frame)
        self.verticalLayout_13.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.reset_pass_title_frame = QtWidgets.QFrame(self.reset_pass_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_pass_title_frame.sizePolicy().hasHeightForWidth())
        self.reset_pass_title_frame.setSizePolicy(sizePolicy)
        self.reset_pass_title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.reset_pass_title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.reset_pass_title_frame.setObjectName("reset_pass_title_frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.reset_pass_title_frame)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.reset_pass_title = QtWidgets.QLabel(self.reset_pass_title_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_pass_title.sizePolicy().hasHeightForWidth())
        self.reset_pass_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.reset_pass_title.setFont(font)
        self.reset_pass_title.setStyleSheet("color: white")
        self.reset_pass_title.setObjectName("reset_pass_title")
        self.verticalLayout_14.addWidget(self.reset_pass_title)
        self.verticalLayout_13.addWidget(self.reset_pass_title_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_10 = QtWidgets.QFrame(self.reset_pass_frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_15.setSpacing(30)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.username = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username.sizePolicy().hasHeightForWidth())
        self.username.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.username.setFont(font)
        self.username.setTabletTracking(True)
        self.username.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.username.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 1px solid #33fcff;\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 7px\n"
"")
        self.username.setText("")
        self.username.setObjectName("username")
        self.verticalLayout_15.addWidget(self.username)
        self.current_pass_input = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_pass_input.sizePolicy().hasHeightForWidth())
        self.current_pass_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.current_pass_input.setFont(font)
        self.current_pass_input.setTabletTracking(True)
        self.current_pass_input.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.current_pass_input.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 1px solid #33fcff;\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 7px\n"
"")
        self.current_pass_input.setText("")
        self.current_pass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.current_pass_input.setObjectName("current_pass_input")
        self.verticalLayout_15.addWidget(self.current_pass_input)
        self.new_pass_input = QtWidgets.QLineEdit(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setBold(True)
        font.setWeight(75)
        self.new_pass_input.setFont(font)
        self.new_pass_input.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 1px solid #33fcff;\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 7px\n"
"")
        self.new_pass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.new_pass_input.setObjectName("new_pass_input")
        self.verticalLayout_15.addWidget(self.new_pass_input)
        self.confirm_pass_input_2 = QtWidgets.QLineEdit(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setBold(True)
        font.setWeight(75)
        self.confirm_pass_input_2.setFont(font)
        self.confirm_pass_input_2.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 1px solid #33fcff;\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 7px\n"
"")
        self.confirm_pass_input_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_pass_input_2.setObjectName("confirm_pass_input_2")
        self.verticalLayout_15.addWidget(self.confirm_pass_input_2)
        self.verticalLayout_13.addWidget(self.frame_10, 0, QtCore.Qt.AlignTop)
        self.reset_pass_btn_frame = QtWidgets.QFrame(self.reset_pass_frame)
        self.reset_pass_btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.reset_pass_btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.reset_pass_btn_frame.setObjectName("reset_pass_btn_frame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.reset_pass_btn_frame)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.reset_pass_btn = QtWidgets.QPushButton(self.reset_pass_btn_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_pass_btn.sizePolicy().hasHeightForWidth())
        self.reset_pass_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.reset_pass_btn.setFont(font)
        self.reset_pass_btn.setStyleSheet("#reset_pass_btn {\n"
"    background-color: #335eff;       /* Blue background */\n"
"    color: white;                   /* White text */\n"
"    font-size: 16px;                /* Text size */\n"
"    font-weight: bold;              /* Bold text */\n"
"    border:none;      /* Border with a darker blue */\n"
"    border-radius: 5px;            /* Rounded corners */\n"
"    padding: 10px 20px;             /* Internal padding */\n"
"}\n"
"\n"
"#reset_pass_btn:hover {\n"
"    background-color: #5e33ff;      /* Darker blue on hover */\n"
"}\n"
"\n"
"#reset_pass_btn:pressed {\n"
"    background-color: #350e95;      /* Dark blue when pressed */\n"
"    color: #e6e6e6;                 /* Slightly lighter text */\n"
"}\n"
"")
        self.reset_pass_btn.setObjectName("reset_pass_btn")
        self.verticalLayout_16.addWidget(self.reset_pass_btn)
        self.verticalLayout_13.addWidget(self.reset_pass_btn_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.notify_frame_2 = QtWidgets.QFrame(self.reset_pass_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notify_frame_2.sizePolicy().hasHeightForWidth())
        self.notify_frame_2.setSizePolicy(sizePolicy)
        self.notify_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.notify_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.notify_frame_2.setObjectName("notify_frame_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.notify_frame_2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.notify_message_2 = QtWidgets.QLineEdit(self.notify_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notify_message_2.sizePolicy().hasHeightForWidth())
        self.notify_message_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setBold(True)
        font.setWeight(75)
        self.notify_message_2.setFont(font)
        self.notify_message_2.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border: none;\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom: 7px\n"
"")
        self.notify_message_2.setText("")
        self.notify_message_2.setAlignment(QtCore.Qt.AlignCenter)
        self.notify_message_2.setObjectName("notify_message_2")
        self.verticalLayout_17.addWidget(self.notify_message_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_13.addWidget(self.notify_frame_2, 0, QtCore.Qt.AlignHCenter)
        self.frame_12 = QtWidgets.QFrame(self.reset_pass_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.go_to_login = QtWidgets.QPushButton(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        font.setUnderline(True)
        self.go_to_login.setFont(font)
        self.go_to_login.setStyleSheet("border: none;\n"
"color: white")
        self.go_to_login.setObjectName("go_to_login")
        self.horizontalLayout_6.addWidget(self.go_to_login, 0, QtCore.Qt.AlignLeft)
        self.go_to_signup = QtWidgets.QPushButton(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        font.setUnderline(True)
        self.go_to_signup.setFont(font)
        self.go_to_signup.setStyleSheet("border: none;\n"
"color: white")
        self.go_to_signup.setObjectName("go_to_signup")
        self.horizontalLayout_6.addWidget(self.go_to_signup, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_13.addWidget(self.frame_12)
        self.horizontalLayout_5.addWidget(self.reset_pass_frame)
        self.support_frame_6 = QtWidgets.QFrame(self.reset_pass_main_frame)
        self.support_frame_6.setStyleSheet("")
        self.support_frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.support_frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.support_frame_6.setObjectName("support_frame_6")
        self.horizontalLayout_5.addWidget(self.support_frame_6)
        self.verticalLayout_18.addWidget(self.reset_pass_main_frame)
        self.stackedWidget.addWidget(self.reset_pass_page)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Log In"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.login_button.setText(_translate("MainWindow", "Login"))
        self.pushButton.setText(_translate("MainWindow", "Sign up"))
        self.pushButton_2.setText(_translate("MainWindow", "Reset Password"))
        self.signup_title.setText(_translate("MainWindow", "Sign up"))
        self.username_input.setPlaceholderText(_translate("MainWindow", "Username"))
        self.pass_input.setPlaceholderText(_translate("MainWindow", "Password"))
        self.confirm_pass_input.setPlaceholderText(_translate("MainWindow", "Confirm Password"))
        self.signup_button.setText(_translate("MainWindow", "Create Account"))
        self.back_to_login.setText(_translate("MainWindow", "Log in"))
        self.change_pass_button.setText(_translate("MainWindow", "Reset Password"))
        self.reset_pass_title.setText(_translate("MainWindow", "Reset password"))
        self.username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.current_pass_input.setPlaceholderText(_translate("MainWindow", "Current Password"))
        self.new_pass_input.setPlaceholderText(_translate("MainWindow", "New Password"))
        self.confirm_pass_input_2.setPlaceholderText(_translate("MainWindow", "Confirm New Password"))
        self.reset_pass_btn.setText(_translate("MainWindow", "Reset Password"))
        self.go_to_login.setText(_translate("MainWindow", "Log in"))
        self.go_to_signup.setText(_translate("MainWindow", "Sign up"))
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
